services:
  django:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.local
      - GUNICORN_RELOAD=true
    env_file:
      - .env
    depends_on:
      - db
    command: bash -c "python manage.py migrate --settings=config.settings.local && gunicorn config.wsgi:application -c gunicorn.conf.py"

  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=myproject
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5433:5432"

volumes:
  postgres_data: